### ISSUE TITLE
Icons not loading in demos

### ISSUE THREAD

**Issue by JuanCaicedo** [JuanCaicedo/oboe.js-website#2]
If you look at the demos on the current [Oboe.js website](I'm trying to find out how the circles in these animations get loaded http://www.oboejs.com/), there are little circle icons that show up.

Those are missing in the [static site version](http://www.juancaicedo.com/oboe.js-website/).

From what I can tell, we're loading all the svg assets for the demos as part of [this partial](https://github.com/JuanCaicedo/oboe.js-website/blob/master/partials/templates.handlebars), which is included in all pages.

Another idea is that maybe the icons are actually being included, but they're just not getting animated and so they always stay out of view.

Let me know if you need some help running the site!

**Comment by josiahsprague** [comment]
What's the difference between the current website and the static version?

**Comment by JuanCaicedo** [comment]
The current website is a node server that serves a dynamic page. The static version is static html pages generated with a build system that tries to leverage all the same code. The entry point for the server is [here](https://github.com/JuanCaicedo/oboe.js-website/blob/master/index.js) and the build script for the static pages is [here](https://github.com/JuanCaicedo/oboe.js-website/blob/master/build-static.js).

I'm still bringing in assets, so it's possible I missed some.

**Comment by patrickkettner** [comment]
[current website snapshotted for posterity](https://web.archive.org/web/20160424215839/http://oboejs.com/)

not sure why it is happening but on the static version of the site, the [r attr](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r) is left blank,

![image](https://cloud.githubusercontent.com/assets/465414/14770883/e3041352-0a48-11e6-94f6-1d0edd687b11.png)

compared with the live site, 

![image](https://cloud.githubusercontent.com/assets/465414/14770885/f1065262-0a48-11e6-9ba4-148138b17be3.png)

and [according to spec](https://www.w3.org/TR/SVG/shapes.html#CircleElementRAttribute) a zero value "disables rendering of the element"

**Comment by patrickkettner** [comment]
I imagine that for whatever reason, [{{packetRadius}}](https://github.com/JuanCaicedo/oboe.js-website/blob/master/partials/templates.handlebars#L332) is undefined

**Comment by JuanCaicedo** [comment]
@patrickkettner yes thank! I don't think that value is dynamic (it's [always the same](https://github.com/JuanCaicedo/oboe.js-website/blob/master/index.js#L60)) so I just replaced it with a hard coded value for the static site.
